---
uri: car
schema:
  type: object
  items:
    year:
      type: integer
    model:
      type: string
    extra features:
      type: array
      items:
        type: string
    price: 
      type: real
      minimum: 0.00

---
uri: customer-name
schema:
  oneOf:
    - type: object
      items:
        first name:
          type: string
        last name:
          type: string
      required:
        - first name
        - last name
    - type: string

---
uri: customer
schema:
  type: object
  items:
    name:
      $ref: customer-name
    cars:
      type: hash
      items:
        $ref: car
  required:
    - name
    - cars

---
uri: customer-list
schema:
  type: array
  items:
    $ref: customer